"""Named preset configurations for common XLRON experiments."""

PRESETS = {
    "Blank (defaults)": {},
    "Quick Test: NSFNET KSP-FF": {
        "EVAL_HEURISTIC": True,
        "env_type": "rmsa",
        "topology_name": "nsfnet_deeprmsa_directed",
        "link_resources": 100,
        "k": 5,
        "load": 250,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 1_000_000,
        "NUM_ENVS": 100,
        "path_heuristic": "ksp_ff",
    },
    "RL Training: NSFNET RMSA": {
        "env_type": "rmsa",
        "topology_name": "nsfnet_deeprmsa_directed",
        "link_resources": 100,
        "k": 5,
        "load": 250,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "truncate_holding_time": True,
        "TOTAL_TIMESTEPS": 100_000_000,
        "NUM_ENVS": 2000,
        "ROLLOUT_LENGTH": 150,
        "LR": 5e-4,
    },
    "RL Training: COST239 RMSA": {
        "env_type": "rmsa",
        "topology_name": "cost239_deeprmsa_directed",
        "link_resources": 100,
        "k": 5,
        "load": 250,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "truncate_holding_time": True,
        "TOTAL_TIMESTEPS": 100_000_000,
        "NUM_ENVS": 2000,
        "ROLLOUT_LENGTH": 150,
        "LR": 5e-4,
    },
    "RL Training: NSFNET RSA": {
        "env_type": "rsa",
        "topology_name": "nsfnet_deeprmsa_directed",
        "link_resources": 100,
        "k": 5,
        "load": 250,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "truncate_holding_time": True,
        "TOTAL_TIMESTEPS": 100_000_000,
        "NUM_ENVS": 2000,
        "ROLLOUT_LENGTH": 150,
        "LR": 5e-4,
    },
    "RSA GN Model Eval: NSFNET KSP-FF": {
        "EVAL_HEURISTIC": True,
        "env_type": "rsa_gn_model",
        "topology_name": "nsfnet_deeprmsa_directed",
        "link_resources": 100,
        "k": 5,
        "load": 250,
        "max_requests": 1000,
        "continuous_operation": False,
        "ENV_WARMUP_STEPS": 0,
        "TOTAL_TIMESTEPS": 10_000,
        "NUM_ENVS": 1,
        "incremental_loading": True,
        "STEPS_PER_INCREMENT": 1_000,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_gn_model.csv",
    },
    "RMSA GN Model Eval: NSFNET KSP-FF": {
        "EVAL_HEURISTIC": True,
        "env_type": "rmsa_gn_model",
        "topology_name": "nsfnet_deeprmsa_directed",
        "link_resources": 100,
        "k": 5,
        "load": 250,
        "continuous_operation": False,
        "ENV_WARMUP_STEPS": 0,
        "max_requests": 1000,
        "TOTAL_TIMESTEPS": 10_000,
        "NUM_ENVS": 1,
        "incremental_loading": True,
        "STEPS_PER_INCREMENT": 1_000,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_gn_model.csv",
    },
    "Gerard 2025 recreation": {
        "EVAL_HEURISTIC": True,
        "env_type": "rsa_gn_model",
        "topology_name": "three_node_chain_undirected",
        "link_resources": 91,
        "k": 2,
        "slot_size": 100.0,
        "guardband": 0,
        "values_bw": "100",
        "band_preference": "C,L",
        "inter_band_gap_ghz": 275.0,
        "slots_per_band": "45,45",
        "span_length": 100.0,
        "nonlinear_coefficient": 0.9e-3,  # 0.71e-3 depending on refractive index
        "dispersion_coeff": 21e-6,
        "dispersion_slope": 60,
        "raman_gain_slope": 1.0e-17,
        "attenuation": 3.68e-5,
        "use_raman_amp": True,
        "raman_pump_power_bw": "0.203839,0.101862,0.101811,0.101739,0.10167",#"0.36314,0.316613,0.0139506,0.00224123,0.000757479", #"0.161131,0.136963,0.12465,0.119438,0.121875",
        "raman_pump_freq_bw": "200.5e12,203.1e12,205.7e12,208.4e12,211.1e12",
        "span_lumped_loss_db": 1.0,
        "fec_rate": 0.838,
        "beta_fec": 1.5e-2,
        "coherent": True,
        "custom_traffic_matrix_csv_filepath": "xlron/data/topologies/three_node_chain_traffic_0to2.csv",
        "incremental_loading": True,
        "max_requests": 90,
        "TOTAL_TIMESTEPS": 90,
        "NUM_ENVS": 1,
        "STEPS_PER_INCREMENT": 100,
        "path_heuristic": "ksp_ff",
        "num_subchannels": 8,
        "power_per_channel_per_band": "1.6756,2.5809",
        "calc_minimum_osnr": True,
        "launch_power_csv": "./experimental/lp.csv",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations.csv",
        "band_data_filepath": "./xlron/data/gn_model/band_data/band_data_gerard2025.csv",
        "noise_data_filepath": "./xlron/data/gn_model/transceiver_amplifier_data/transceiver_amplifier_data_gerard2025.csv",
    },
    "Gerard 2025 recreation RMSA": {
        "EVAL_HEURISTIC": True,
        "env_type": "rmsa_gn_model",
        "topology_name": "three_node_chain_undirected",
        "link_resources": 91,
        "k": 2,
        "slot_size": 100.0,
        "guardband": 0,
        "values_bw": "800",
        "band_preference": "C,L",
        "inter_band_gap_ghz": 275.0,
        "slots_per_band": "45,45",
        "span_length": 100.0,
        "nonlinear_coefficient": 0.9e-3,  # 0.71e-3 depending on refractive index
        "dispersion_coeff": 21e-6,
        "dispersion_slope": 60,
        "raman_gain_slope": 1.0e-17,
        "attenuation": 3.68e-5,
        "use_raman_amp": True,
        "raman_pump_power_bw": "0.36314,0.316613,0.0139506,0.00224123,0.000757479", #"0.161131,0.136963,0.12465,0.119438,0.121875",
        "raman_pump_freq_bw": "200.5e12,203.1e12,205.7e12,208.4e12,211.1e12",
        "span_lumped_loss_db": 1.0,
        "fec_rate": 0.838,
        "beta_fec": 1.5e-2,
        "coherent": True,
        "custom_traffic_matrix_csv_filepath": "xlron/data/topologies/three_node_chain_traffic_0to2.csv",
        "incremental_loading": True,
        "max_requests": 90,
        "TOTAL_TIMESTEPS": 90,
        "NUM_ENVS": 1,
        "STEPS_PER_INCREMENT": 100,
        "path_heuristic": "ksp_ff",
        "num_subchannels": 8,
        "power_per_channel_per_band": "1.6756,2.5809",
        "calc_minimum_osnr": False,
        "launch_power_csv": "./experimental/lp.csv",
        "modulations_csv_filepath": "./xlron/data/modulations/pcs_64qam.csv",
        "band_data_filepath": "./xlron/data/gn_model/band_data_gerard2025.csv",
        "noise_data_filepath": "./xlron/data/gn_model/transceiver_amplifier_data_gerard2025.csv",
    },
    # JOCN 2024 Heuristic Evaluation Bounds Presets
    "JOCN24: DeepRMSA NSFNET": {
        "EVAL_HEURISTIC": True,
        "env_type": "rmsa",
        "topology_name": "nsfnet_deeprmsa_directed",
        "link_resources": 100,
        "k": 50,
        "load": 200,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "mean_service_holding_time": 20,
        "truncate_holding_time": True,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: DeepRMSA COST239": {
        "EVAL_HEURISTIC": True,
        "env_type": "rmsa",
        "topology_name": "cost239_deeprmsa_directed",
        "link_resources": 100,
        "k": 50,
        "load": 500,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "mean_service_holding_time": 20,
        "truncate_holding_time": True,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: GCN-RMSA USNET": {
        "EVAL_HEURISTIC": True,
        "env_type": "rmsa",
        "topology_name": "usnet_gcnrnn_directed",
        "link_resources": 100,
        "k": 50,
        "load": 400,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "mean_service_holding_time": 20,
        "truncate_holding_time": True,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: MaskRSA NSFNET undirected": {
        "EVAL_HEURISTIC": True,
        "env_type": "rmsa",
        "topology_name": "nsfnet_deeprmsa_undirected",
        "link_resources": 80,
        "k": 50,
        "load": 115,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "max_bw": 50,
        "guardband": 0,
        "slot_size": 12.5,
        "mean_service_holding_time": 12,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: MaskRSA JPN48": {
        "EVAL_HEURISTIC": True,
        "env_type": "rmsa",
        "topology_name": "jpn48_undirected",
        "link_resources": 80,
        "k": 50,
        "load": 200,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "max_bw": 50,
        "guardband": 0,
        "slot_size": 12.5,
        "mean_service_holding_time": 12,
        "path_heuristic": "ff_ksp",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: PtrNet-RSA-40 NSFNET": {
        "EVAL_HEURISTIC": True,
        "env_type": "rsa",
        "topology_name": "nsfnet_deeprmsa_undirected",
        "link_resources": 40,
        "k": 50,
        "load": 225,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "slot_size": 1,
        "guardband": 0,
        "values_bw": "1",
        "mean_service_holding_time": 10,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: PtrNet-RSA-40 COST239": {
        "EVAL_HEURISTIC": True,
        "env_type": "rsa",
        "topology_name": "cost239_ptrnet_real_undirected",
        "link_resources": 40,
        "k": 50,
        "load": 460,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "slot_size": 1,
        "guardband": 0,
        "values_bw": "1",
        "mean_service_holding_time": 10,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: PtrNet-RSA-40 USNET": {
        "EVAL_HEURISTIC": True,
        "env_type": "rsa",
        "topology_name": "usnet_ptrnet_undirected",
        "link_resources": 40,
        "k": 50,
        "load": 250,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "slot_size": 1,
        "guardband": 0,
        "values_bw": "1",
        "mean_service_holding_time": 10,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: PtrNet-RSA-80 NSFNET": {
        "EVAL_HEURISTIC": True,
        "env_type": "rsa",
        "topology_name": "nsfnet_deeprmsa_undirected",
        "link_resources": 80,
        "k": 50,
        "load": 250,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "slot_size": 1,
        "guardband": 0,
        "values_bw": "1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,3,3,4",
        "mean_service_holding_time": 10,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: PtrNet-RSA-80 COST239": {
        "EVAL_HEURISTIC": True,
        "env_type": "rsa",
        "topology_name": "cost239_ptrnet_real_undirected",
        "link_resources": 80,
        "k": 50,
        "load": 525,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "slot_size": 1,
        "guardband": 0,
        "values_bw": "1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,3,3,4",
        "mean_service_holding_time": 10,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
    "JOCN24: PtrNet-RSA-80 USNET": {
        "EVAL_HEURISTIC": True,
        "env_type": "rsa",
        "topology_name": "usnet_ptrnet_undirected",
        "link_resources": 80,
        "k": 50,
        "load": 275,
        "continuous_operation": True,
        "ENV_WARMUP_STEPS": 3000,
        "TOTAL_TIMESTEPS": 20_000_000,
        "NUM_ENVS": 2000,
        "slot_size": 1,
        "guardband": 0,
        "values_bw": "1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,3,3,4",
        "mean_service_holding_time": 10,
        "path_heuristic": "ksp_ff",
        "modulations_csv_filepath": "./xlron/data/modulations/modulations_deeprmsa.csv",
    },
}
