codecov:
  require_ci_to_pass: yes

coverage:
  precision: 0
  round: up
  range: "30...70"
  status:
    project: # settings affecting project coverage
      default:
        threshold: 40%  # allow for 40% reduction of coverage without failing
    patch:
      default:
        target: 0%  # new contributions should have a coverage at least equal to target

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true

ignore:
  - ".github/"
  - "config/"
  - "docs/"
  - "notebooks/"
  - "site/"
  - "topologies/"
  - ".gitignore"
  - "LICENSE"
  - "mkdocs.yml"
  - "_version.py"
  - "setup.py"
  - "requirements.txt"
  - "pyproject.toml"
  - "poetry.lock"
  - "README.md"
  - "xlron/environments/vone/**/*"
  - "xlron/models/**/*"
  - "xlron/train/**/*"
