"""Regenerate docs/flags_reference.md from the flag definitions in xlron/parameter_flags.py.

Usage:
    uv run python docs/gen_flags_reference.py           # rewrite docs/flags_reference.md
    uv run python docs/gen_flags_reference.py --check   # exit 1 if the committed file is stale

Run automatically in the docs deploy job (see .github/workflows/github-actions.yaml) before
`mkdocs gh-deploy`, so the published command-line reference cannot drift from the code.
Importing only xlron.parameter_flags keeps this fast (no JAX import) and restricts the
output to XLRON's own flags rather than everything --helpfull would dump.
"""

import pathlib
import sys

from absl import flags

import xlron.parameter_flags  # noqa: F401  (registers all DEFINE_* flags)

OUTPUT_PATH = pathlib.Path(__file__).parent / "flags_reference.md"

HEADER = """# Command-line Options

<!-- This file is auto-generated by docs/gen_flags_reference.py - do not edit by hand. -->

```commandline
"""

FOOTER = "```\n"


def generate() -> str:
    module_help = flags.FLAGS.module_help(xlron.parameter_flags)
    return HEADER + module_help.strip("\n") + "\n" + FOOTER


def main() -> int:
    content = generate()
    if "--check" in sys.argv[1:]:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text() != content:
            print(
                f"{OUTPUT_PATH} is stale. Regenerate it with: "
                "uv run python docs/gen_flags_reference.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH} is up to date.")
        return 0
    OUTPUT_PATH.write_text(content)
    print(f"Wrote {OUTPUT_PATH}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
